#!/bin/bash

MIRROR_URI=""
DST_PATH="${PWD}/conf/site.conf"

function usage_exit() {
    echo "Usage: $0 [-O output_path] [-h] URI"
    echo "       -O(--output): The output path for site.conf"
    echo "       -h(--help)     : help(this message)"
    exit 0
}

function check_args() {
    declare args
    args=$(getopt -o O:h -l output:,help -- "$@") || exit 22
    eval set -- "$args"

    # loop for parsing
    while [ $# -gt 0 ]; do
        case $1 in
	    -O | --output)
		DST_PATH="$2"
		shift 2
		;;
            -h | --help)
                usage_exit
                shift
                ;;
            --)
                shift
                break
                ;;
        esac
    done

    MIRROR_URI=$1
    if [ "${MIRROR_URI}" = "" ]; then
        usage_exit
    fi

    echo "MIRROR_URL = ${MIRROR_URI}"
    echo "DST_PATH   = ${DST_PATH}"
}

function gen_site_conf() {
    if [ -e "${DST_PATH}" ]; then
	echo "${DST_PATH} already exists."
	exit 1
    fi
    cat << EOF >> "${DST_PATH}"
# 
# This file is generated by gen-site-conf.sh
# 

INHERIT += "own-mirrors"
SOURCE_MIRROR_URL = "${MIRROR_URI}"
EOF
}

check_args "$@"
gen_site_conf
